### ISSUE TITLE
idea clon项目启动失败

### ISSUE THREAD

**Issue by yangheiya** [dounine/japi#60]
启动后台和文档界面都抛出异常，后台：Execution failed for task ':server:findMainClass'.。文档： Cannot find module 'koa'

**Comment by yangheiya** [comment]
后台：
Worker lease root.1 completed (0 worker(s) in use)
Daemon worker Thread 3: released lock on root.1
11:07:59.415 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:07:59.415 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:07:59.415 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:07:59.415 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':server:findMainClass'.
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.gradle.api.tasks.SourceSetOutput.getClassesDir()Ljava/io/File;
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
11:07:59.416 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 5s
11:07:59.417 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 5 actionable tasks: 1 executed, 4 up-to-date
11:07:59.431 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
11:07:59.431 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
-----------------------------------------------------------
文档界面：
Error: Cannot find module 'koa'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\project\japi\node\app.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by yangheiya** [comment]
求大佬解惑，初次用gradle。
